name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: patientmanagementacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push API Image
      run: |
        docker build -t patientmanagementacr.azurecr.io/patient_management_api:latest -f api/Dockerfile .
        docker push patientmanagementacr.azurecr.io/patient_management_api:latest

    - name: Build and Push Celery Worker Image
      run: |
        docker build -t patientmanagementacr.azurecr.io/patient_management_celery:latest -f celery/Dockerfile .
        docker push patientmanagementacr.azurecr.io/patient_management_celery:latest

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy API to Azure
      run: |
        az containerapp update \
          --name patient-management-api \
          --resource-group patient-management-rg \
          --image patientmanagementacr.azurecr.io/patient_management_api:latest

    - name: Deploy Celery to Azure
      run: |
        az containerapp update \
          --name patient-management-celery \
          --resource-group patient-management-rg \
          --image patientmanagementacr.azurecr.io/patient_management_celery:latest
